name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main # If your main branch is called 'master', change this
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # STEP 1: Downloads your code
      - uses: actions/checkout@v4
        
      # STEP 2: Deploys the code it just downloaded
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: mirus-issue-tracker
          channelId: live # This line forces it to deploy to the live site
